import type { Category, CampusLocation, Deal, FoodItem } from './types';

export const categories: Category[] = [
  { id: 'pizza', name: 'Pizza', icon: 'Pizza', description: 'Hot & cheesy' },
  { id: 'burgers', name: 'Burgers', icon: 'Burger', description: 'Juicy & loaded' },
  { id: 'rolls', name: 'Rolls & Wraps', icon: 'Sandwich', description: 'Grab & go' },
  { id: 'south-indian', name: 'South Indian', icon: 'Utensils', description: 'Crispy & savoury' },
  { id: 'rice-noodles', name: 'Rice & Noodles', icon: 'RiceBowl', description: 'Wok-tossed meals' },
  { id: 'snacks', name: 'Snacks', icon: 'Sandwich', description: 'Quick bites' },
  { id: 'beverages', name: 'Beverages', icon: 'CupSoda', description: 'Drinks & shakes' },
];

export const campusLocations: CampusLocation[] = [
  { id: 'main', name: 'Main Canteen', blocks: ['Ground Floor', 'First Floor', 'Terrace'] },
  { id: 'foodcourt', name: 'Food Court', blocks: ['Block A', 'Block B', 'Block C'] },
  { id: 'hostel', name: 'Hostel Block', blocks: ['Hostel 1', 'Hostel 2', 'Hostel 3'] },
  { id: 'library', name: 'Library Cafe', blocks: ['Reading Hall', 'Lounge Area'] },
];

export const deals: Deal[] = [
  {
    id: 'deal1',
    title: 'Lunch Combo',
    description: 'Paneer Rice + Cold Coffee',
    tag: 'COMBO',
    items: 'Paneer Fried Rice + Cold Coffee',
    price: 140,
    originalPrice: 160,
    image: 'https://images.pexels.com/photos/8992927/pexels-photo-8992927.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
  },
  {
    id: 'deal2',
    title: 'Snack Attack',
    description: 'Samosa + Fresh Lime',
    tag: 'STUDENT DEAL',
    items: '2 Samosa + Fresh Lime',
    price: 60,
    originalPrice: 90,
    image: 'https://images.pexels.com/photos/8992923/pexels-photo-8992923.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
  },
  {
    id: 'deal3',
    title: 'Roll Feast',
    description: 'Any 2 Rolls',
    tag: 'LIMITED TIME',
    items: '2 Paneer or Chicken Rolls',
    price: 120,
    originalPrice: 160,
    image: 'https://images.pexels.com/photos/5713744/pexels-photo-5713744.jpeg?auto=compress&cs=tinysrgb&h=400&w=400',
  },
];

export const foodItems: FoodItem[] = [
  // PIZZA
  {
    id: 'margherita-pizza',
    name: 'Margherita Pizza',
    description: 'Classic pizza with mozzarella, basil, and tomato sauce.',
    longDescription:
      'A timeless classic — hand-stretched dough topped with tangy tomato sauce, fresh mozzarella cheese, and fragrant basil leaves. Baked in a stone oven for that perfect crispy-yet-chewy crust. Simple, comforting, and always satisfying.',
    ingredients: ['Pizza dough', 'Tomato sauce', 'Mozzarella', 'Fresh basil', 'Olive oil', 'Oregano'],
    price: 120,
    image: 'https://images.pexels.com/photos/15550301/pexels-photo-15550301.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'pizza',
    isVeg: true,
    rating: 4.5,
    ratingCount: 152,
    prepTime: 20,
    location: 'Food Court',
    popular: true,
    reviews: [
      { id: 'r1', author: 'Siddharth R.', rating: 5, date: '1 day ago', comment: 'Best pizza on campus. The crust is perfectly crispy!' },
      { id: 'r2', author: 'Anjali P.', rating: 4, date: '4 days ago', comment: 'Simple but so good. Reminds me of home.' },
    ],
  },
  {
    id: 'paneer-tikka-pizza',
    name: 'Paneer Tikka Pizza',
    description: 'Desi-style pizza with spiced paneer tikka and capsicum.',
    longDescription:
      'A fusion favourite — crispy pizza base loaded with tikka-spiced paneer cubes, crunchy capsicum, and red onion, all smothered in melted cheese. Topped with a drizzle of mint chutney for that extra kick. A campus crowd-puller.',
    ingredients: ['Pizza dough', 'Paneer tikka', 'Capsicum', 'Red onion', 'Mozzarella', 'Mint chutney', 'Tikka masala'],
    price: 150,
    image: 'https://images.pexels.com/photos/19081131/pexels-photo-19081131.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'pizza',
    isVeg: true,
    rating: 4.6,
    ratingCount: 187,
    prepTime: 22,
    location: 'Food Court',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Nikita J.', rating: 5, date: '2 days ago', comment: 'The paneer tikka topping is genius. So flavourful!' },
      { id: 'r2', author: 'Aryan S.', rating: 5, date: '1 week ago', comment: 'Worth the 150 rupees. Generous paneer pieces.' },
    ],
  },
  {
    id: 'corn-cheese-pizza',
    name: 'Corn & Cheese Pizza',
    description: 'Sweet corn and extra cheese on a golden crust.',
    longDescription:
      "A cheese lover's dream — loaded with sweet corn kernels, extra mozzarella, and a sprinkle of herbs on a golden-baked crust. Gooey, sweet, and savoury all at once. Perfect for sharing with your study group.",
    ingredients: ['Pizza dough', 'Sweet corn', 'Extra mozzarella', 'Bell pepper', 'Oregano', 'Chili flakes'],
    price: 130,
    image: 'https://images.pexels.com/photos/29021748/pexels-photo-29021748.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'pizza',
    isVeg: true,
    rating: 4.4,
    ratingCount: 118,
    prepTime: 20,
    location: 'Food Court',
    reviews: [
      { id: 'r1', author: 'Rohan M.', rating: 4, date: '3 days ago', comment: 'Extra cheese is always a good idea. Loved it!' },
      { id: 'r2', author: 'Divya K.', rating: 5, date: '1 week ago', comment: 'Corn and cheese combo is amazing. So cheesy!' },
    ],
  },
  {
    id: 'chicken-cheese-pizza',
    name: 'Chicken Cheese Pizza',
    description: 'Loaded with tandoori chicken, onions, and extra cheese.',
    longDescription:
      'A protein-packed pizza — tender tandoori chicken pieces, sliced onions, and a double layer of melted mozzarella on a crispy stone-baked base. Spiced with a house blend that makes every bite memorable. The ultimate post-exam celebration meal.',
    ingredients: ['Pizza dough', 'Tandoori chicken', 'Onion', 'Extra mozzarella', 'Chili flakes', 'Coriander'],
    price: 170,
    image: 'https://images.pexels.com/photos/9792460/pexels-photo-9792460.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'pizza',
    isVeg: false,
    rating: 4.7,
    ratingCount: 203,
    prepTime: 25,
    location: 'Food Court',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Kabir D.', rating: 5, date: '1 day ago', comment: 'Tandoori chicken on pizza is next level. Obsessed!' },
      { id: 'r2', author: 'Sneha R.', rating: 5, date: '5 days ago', comment: 'So much chicken and cheese. Total value for money.' },
    ],
  },
  {
    id: 'spicy-veg-pizza',
    name: 'Spicy Veg Pizza',
    description: 'Fiery veggie pizza with jalapenos, olives, and chili.',
    longDescription:
      'For those who like it hot — a crispy base loaded with jalapenos, black olives, onions, and bell peppers, dusted with chili flakes and oregano. Every slice packs a spicy, savoury punch that pairs perfectly with a cold drink.',
    ingredients: ['Pizza dough', 'Jalapenos', 'Black olives', 'Onion', 'Bell pepper', 'Chili flakes', 'Mozzarella'],
    price: 140,
    image: 'https://images.pexels.com/photos/8609973/pexels-photo-8609973.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'pizza',
    isVeg: true,
    rating: 4.3,
    ratingCount: 95,
    prepTime: 20,
    location: 'Food Court',
    reviews: [
      { id: 'r1', author: 'Vikas T.', rating: 4, date: '2 days ago', comment: 'Nice and spicy! Jalapenos add a great kick.' },
      { id: 'r2', author: 'Pallavi S.', rating: 5, date: '1 week ago', comment: 'Perfect amount of heat. My favourite veg pizza on campus.' },
    ],
  },

  // BURGERS
  {
    id: 'veg-burger',
    name: 'Veg Burger',
    description: 'Crispy veg patty with lettuce, tomato, and house sauce.',
    longDescription:
      'A golden-fried vegetable patty stacked with fresh lettuce, juicy tomato slices, melted cheese, and a smoky house sauce in a soft sesame bun. A satisfying veggie burger that hits the spot between lectures.',
    ingredients: ['Sesame bun', 'Veg patty', 'Lettuce', 'Tomato', 'Cheese slice', 'House sauce'],
    price: 80,
    image: 'https://images.pexels.com/photos/20741663/pexels-photo-20741663.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'burgers',
    isVeg: true,
    rating: 4.3,
    ratingCount: 134,
    prepTime: 10,
    location: 'Food Court',
    popular: true,
    reviews: [
      { id: 'r1', author: 'Sneha P.', rating: 4, date: '2 days ago', comment: 'Crispy patty and fresh veggies. Great value!' },
      { id: 'r2', author: 'Arjun M.', rating: 5, date: '1 week ago', comment: 'Best veg burger on campus. The sauce is amazing.' },
    ],
  },
  {
    id: 'chicken-burger',
    name: 'Chicken Burger',
    description: 'Juicy grilled chicken patty with cheese and veggies.',
    longDescription:
      'A thick, grilled chicken patty layered with melted cheese, crisp lettuce, onion rings, and tangy mayo in a toasted brioche bun. Hearty, juicy, and packed with flavour — the perfect post-class meal.',
    ingredients: ['Brioche bun', 'Chicken patty', 'Cheese', 'Lettuce', 'Onion ring', 'Mayo'],
    price: 110,
    image: 'https://images.pexels.com/photos/27758748/pexels-photo-27758748.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'burgers',
    isVeg: false,
    rating: 4.6,
    ratingCount: 178,
    prepTime: 12,
    location: 'Food Court',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Rahul V.', rating: 5, date: '1 day ago', comment: 'So juicy! The chicken patty is perfectly grilled.' },
      { id: 'r2', author: 'Ishita B.', rating: 4, date: '4 days ago', comment: 'Fills you up nicely. Cheese melts perfectly.' },
    ],
  },
  {
    id: 'paneer-burger',
    name: 'Paneer Burger',
    description: 'Spiced paneer patty with mint chutney and veggies.',
    longDescription:
      'A tandoori-spiced paneer patty stacked with crunchy lettuce, sliced onions, and a generous spread of mint-coriander chutney in a soft bun. A desi twist on a campus favourite.',
    ingredients: ['Sesame bun', 'Paneer patty', 'Lettuce', 'Onion', 'Mint chutney', 'Cheese'],
    price: 95,
    image: 'https://images.pexels.com/photos/19709551/pexels-photo-19709551.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'burgers',
    isVeg: true,
    rating: 4.4,
    ratingCount: 112,
    prepTime: 10,
    location: 'Food Court',
    reviews: [
      { id: 'r1', author: 'Ananya T.', rating: 5, date: '3 days ago', comment: 'The mint chutney takes this burger to the next level!' },
      { id: 'r2', author: 'Dev P.', rating: 4, date: '1 week ago', comment: 'Paneer is soft and well-spiced. Good portion.' },
    ],
  },

  // ROLLS & WRAPS
  {
    id: 'paneer-roll',
    name: 'Paneer Roll',
    description: 'Soft roti wrap with spiced paneer and chutney.',
    longDescription:
      'A warm, flaky roti wrapped around marinated paneer tikka, crunchy onions, and tangy mint chutney. The ultimate grab-and-go campus snack.',
    ingredients: ['Roti', 'Paneer tikka', 'Onion', 'Mint chutney', 'Chaat masala', 'Lemon'],
    price: 70,
    image: 'https://images.pexels.com/photos/2955819/pexels-photo-2955819.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'rolls',
    isVeg: true,
    rating: 4.4,
    ratingCount: 156,
    prepTime: 8,
    location: 'Food Court',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Ananya T.', rating: 5, date: '4 days ago', comment: 'The chutney makes it! So flavourful for 70 rupees.' },
      { id: 'r2', author: 'Aditya G.', rating: 4, date: '2 weeks ago', comment: 'Great on-the-go wrap. Sometimes the roti is a bit dry.' },
    ],
  },
  {
    id: 'chicken-roll',
    name: 'Chicken Roll',
    description: 'Chicken tikka wrap with onions and mint chutney.',
    longDescription:
      'Juicy chicken tikka rolled into a soft paratha with crunchy onions, green chutney, and a sprinkle of chaat masala. A filling, flavour-packed campus classic.',
    ingredients: ['Paratha', 'Chicken tikka', 'Onion', 'Mint chutney', 'Chaat masala', 'Egg wash'],
    price: 90,
    image: 'https://images.pexels.com/photos/5713744/pexels-photo-5713744.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'rolls',
    isVeg: false,
    rating: 4.7,
    ratingCount: 245,
    prepTime: 10,
    location: 'Food Court',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Rahul V.', rating: 5, date: '1 day ago', comment: 'Absolute fire. The chicken tikka is perfectly spiced.' },
      { id: 'r2', author: 'Ishita B.', rating: 5, date: '6 days ago', comment: 'Better than any off-campus roll I have had.' },
    ],
  },
  {
    id: 'chicken-shawarma',
    name: 'Chicken Shawarma',
    description: 'Grilled chicken wrap with garlic sauce and pickles.',
    longDescription:
      'Thinly sliced grilled chicken wrapped in a soft pita with fresh veggies, crunchy pickles, and a creamy garlic sauce. A Middle Eastern campus favourite that is perfect for a quick, filling bite.',
    ingredients: ['Pita bread', 'Grilled chicken', 'Lettuce', 'Pickles', 'Garlic sauce', 'Tomato'],
    price: 100,
    image: 'https://images.pexels.com/photos/6416559/pexels-photo-6416559.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'rolls',
    isVeg: false,
    rating: 4.5,
    ratingCount: 167,
    prepTime: 10,
    location: 'Food Court',
    reviews: [
      { id: 'r1', author: 'Karan D.', rating: 5, date: '2 days ago', comment: 'The garlic sauce is incredible. So filling!' },
      { id: 'r2', author: 'Meera L.', rating: 4, date: '1 week ago', comment: 'Great wrap for the price. Chicken is tender.' },
    ],
  },

  // SOUTH INDIAN
  {
    id: 'masala-dosa',
    name: 'Masala Dosa',
    description: 'Crispy dosa stuffed with spiced potato masala.',
    longDescription:
      'A golden, crispy rice-batter dosa wrapped around a generously spiced potato-onion masala. Served with coconut chutney and hot sambar. A South Indian campus staple.',
    ingredients: ['Rice batter', 'Potato', 'Onion', 'Mustard seeds', 'Curry leaves', 'Coconut chutney', 'Sambar'],
    price: 60,
    image: 'https://images.pexels.com/photos/8992918/pexels-photo-8992918.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'south-indian',
    isVeg: true,
    rating: 4.5,
    ratingCount: 189,
    prepTime: 12,
    location: 'Main Canteen',
    popular: true,
    reviews: [
      { id: 'r1', author: 'Deepak N.', rating: 5, date: '3 days ago', comment: 'Crispy and golden. Sambar is on point!' },
      { id: 'r2', author: 'Meera L.', rating: 4, date: '1 week ago', comment: 'Perfect breakfast before the 8 AM lecture.' },
    ],
  },
  {
    id: 'idli-sambar',
    name: 'Idli Sambar',
    description: 'Steamed rice cakes with sambar and chutney.',
    longDescription:
      'Soft, fluffy steamed rice cakes served with piping hot sambar and two types of chutney — coconut and tomato. A light, healthy, and comforting South Indian breakfast that never goes out of style.',
    ingredients: ['Rice batter', 'Urad dal', 'Sambar', 'Coconut chutney', 'Tomato chutney'],
    price: 45,
    image: 'https://images.pexels.com/photos/5127333/pexels-photo-5127333.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'south-indian',
    isVeg: true,
    rating: 4.2,
    ratingCount: 98,
    prepTime: 10,
    location: 'Main Canteen',
    reviews: [
      { id: 'r1', author: 'Sahil M.', rating: 4, date: '2 days ago', comment: 'Light and filling. Perfect before a morning class.' },
    ],
  },

  // RICE & NOODLES
  {
    id: 'paneer-fried-rice',
    name: 'Paneer Fried Rice',
    description: 'Wok-tossed basmati rice with spiced paneer and veggies.',
    longDescription:
      'A campus favourite — fluffy basmati rice stir-fried in a hot wok with marinated paneer cubes, shredded carrots, capsicum, and a blend of Indo-Chinese spices. Served in generous student portions.',
    ingredients: ['Basmati rice', 'Paneer', 'Capsicum', 'Carrot', 'Soy sauce', 'Green onion', 'Garlic'],
    price: 90,
    image: 'https://images.pexels.com/photos/29631461/pexels-photo-29631461.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'rice-noodles',
    isVeg: true,
    rating: 4.5,
    ratingCount: 218,
    prepTime: 15,
    location: 'Main Canteen',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Aarav S.', rating: 5, date: '2 days ago', comment: 'Best fried rice on campus, hands down. Portion size is huge!' },
      { id: 'r2', author: 'Priya M.', rating: 4, date: '1 week ago', comment: 'Paneer is super soft. Could use a bit more spice though.' },
      { id: 'r3', author: 'Rohit K.', rating: 5, date: '2 weeks ago', comment: 'My go-to lunch between lectures. Never disappoints.' },
    ],
  },
  {
    id: 'chicken-rice',
    name: 'Chicken Rice',
    description: 'Stir-fried rice with juicy chicken chunks and herbs.',
    longDescription:
      'Tender chicken pieces wok-fried with basmati rice, aromatic garlic, and a house spice blend. Topped with spring onions for that perfect campus-meal flavour.',
    ingredients: ['Basmati rice', 'Chicken', 'Garlic', 'Soy sauce', 'Spring onion', 'Black pepper'],
    price: 110,
    image: 'https://images.pexels.com/photos/105588/pexels-photo-105588.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'rice-noodles',
    isVeg: false,
    rating: 4.6,
    ratingCount: 301,
    prepTime: 18,
    location: 'Main Canteen',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Karan D.', rating: 5, date: '3 days ago', comment: 'Chicken is so juicy. Worth every rupee.' },
      { id: 'r2', author: 'Neha R.', rating: 4, date: '5 days ago', comment: 'Great after a long lab session. Fills you up properly.' },
    ],
  },
  {
    id: 'veg-noodles',
    name: 'Veg Noodles',
    description: 'Hakka-style noodles with crunchy vegetables.',
    longDescription:
      'Springy Hakka noodles tossed with shredded cabbage, carrots, beans, and bell peppers in a savoury Indo-Chinese sauce. A quick, satisfying meal between classes.',
    ingredients: ['Hakka noodles', 'Cabbage', 'Carrot', 'Beans', 'Bell pepper', 'Soy sauce', 'Garlic'],
    price: 80,
    image: 'https://images.pexels.com/photos/12737657/pexels-photo-12737657.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'rice-noodles',
    isVeg: true,
    rating: 4.3,
    ratingCount: 174,
    prepTime: 12,
    location: 'Food Court',
    popular: true,
    reviews: [
      { id: 'r1', author: 'Sneha P.', rating: 4, date: '1 day ago', comment: 'Veggies are fresh and crunchy. Nice quick option.' },
      { id: 'r2', author: 'Vikram J.', rating: 5, date: '1 week ago', comment: 'Perfect before a 9 AM class. Fast and tasty.' },
    ],
  },

  // SNACKS
  {
    id: 'samosa',
    name: 'Samosa',
    description: 'Flaky pastry with spiced potato-pea filling.',
    longDescription:
      'Golden-fried triangular pastry stuffed with a warmly spiced potato and green pea filling. Served with tamarind chutney. The iconic campus tea-time snack.',
    ingredients: ['Maida', 'Potato', 'Green peas', 'Cumin', 'Coriander', 'Green chili', 'Tamarind chutney'],
    price: 25,
    image: 'https://images.pexels.com/photos/8992923/pexels-photo-8992923.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'snacks',
    isVeg: true,
    rating: 4.2,
    ratingCount: 412,
    prepTime: 6,
    location: 'Library Cafe',
    popular: true,
    reviews: [
      { id: 'r1', author: 'Sahil M.', rating: 4, date: '2 days ago', comment: 'Classic samosa with great chutney. Can not beat 25 rupees.' },
      { id: 'r2', author: 'Riya S.', rating: 5, date: '5 days ago', comment: 'Best evening snack with chai. Always fresh.' },
    ],
  },
  {
    id: 'french-fries',
    name: 'French Fries',
    description: 'Crispy golden fries with peri-peri seasoning.',
    longDescription:
      'Perfectly crispy on the outside, fluffy inside — these golden fries are dusted with peri-peri seasoning and served with ketchup. The ultimate study-break snack.',
    ingredients: ['Potato', 'Peri-peri seasoning', 'Salt', 'Ketchup'],
    price: 60,
    image: 'https://images.pexels.com/photos/27758755/pexels-photo-27758755.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'snacks',
    isVeg: true,
    rating: 4.3,
    ratingCount: 267,
    prepTime: 8,
    location: 'Library Cafe',
    popular: true,
    reviews: [
      { id: 'r1', author: 'Arjun P.', rating: 4, date: '1 day ago', comment: 'Crispy and well-seasoned. Good portion.' },
      { id: 'r2', author: 'Tara K.', rating: 5, date: '1 week ago', comment: 'My study-group always orders these. Perfect munchies.' },
    ],
  },

  // BEVERAGES
  {
    id: 'cold-coffee',
    name: 'Cold Coffee',
    description: 'Creamy blended iced coffee with milk.',
    longDescription:
      'Rich, frothy cold coffee blended with chilled milk, ice cream, and a shot of espresso. Served tall with a thick foam top. The fuel for every exam season.',
    ingredients: ['Coffee', 'Milk', 'Ice cream', 'Ice', 'Sugar', 'Chocolate sauce'],
    price: 70,
    image: 'https://images.pexels.com/photos/38028984/pexels-photo-38028984.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'beverages',
    isVeg: true,
    rating: 4.6,
    ratingCount: 198,
    prepTime: 5,
    location: 'Library Cafe',
    popular: true,
    recommended: true,
    reviews: [
      { id: 'r1', author: 'Nisha A.', rating: 5, date: '2 days ago', comment: 'Survived finals week on this stuff. So creamy!' },
      { id: 'r2', author: 'Dev P.', rating: 4, date: '1 week ago', comment: 'Good coffee hit. Wish it came in a larger size.' },
    ],
  },
  {
    id: 'fresh-lime',
    name: 'Fresh Lime Soda',
    description: 'Refreshing lime soda — sweet, salt, or mixed.',
    longDescription:
      'A zesty, refreshing lime soda made with fresh lemon juice, soda water, and your choice of sweet, salt, or mixed. The perfect thirst-quencher for a hot campus afternoon.',
    ingredients: ['Lime', 'Soda water', 'Sugar', 'Salt', 'Mint leaves'],
    price: 40,
    image: 'https://images.pexels.com/photos/37515882/pexels-photo-37515882.jpeg?auto=compress&cs=tinysrgb&h=600&w=600',
    category: 'beverages',
    isVeg: true,
    rating: 4.1,
    ratingCount: 134,
    prepTime: 3,
    location: 'Food Court',
    reviews: [
      { id: 'r1', author: 'Pooja R.', rating: 4, date: '4 days ago', comment: 'Refreshing after sitting in the sun. Mixed is the best.' },
    ],
  },
];

export const heroImage =
  'https://images.pexels.com/photos/4570082/pexels-photo-4570082.jpeg?auto=compress&cs=tinysrgb&h=800&w=1200';
